/**/callback({"meta": {
  "Cache-Control": "public, max-age=60, s-maxage=60",
  "Vary": "Accept",
  "ETag": "\"b42f7f7b9b2e69686530f8fb4a0a112684e961e85e689a53d79d97fdca40a31e\"",
  "Last-Modified": "Sat, 17 Dec 2022 08:03:55 GMT",
  "Content-Type": "application/javascript; charset=utf-8",
  "X-GitHub-Media-Type": "github.v3; format=json",
  "status": 200,
  "X-RateLimit-Limit": "60",
  "X-RateLimit-Remaining": "59",
  "X-RateLimit-Reset": "1671276013",
  "X-RateLimit-Used": "1",
  "X-RateLimit-Resource": "core"
}, "data": {
  "id": 80234494,
  "node_id": "MDEwOlJlcG9zaXRvcnk4MDIzNDQ5NA==",
  "name": "vanilla-tilt.js",
  "full_name": "micku7zu/vanilla-tilt.js",
  "private": false,
  "owner": {
    "login": "micku7zu",
    "id": 3103859,
    "node_id": "MDQ6VXNlcjMxMDM4NTk=",
    "avatar_url": "https://avatars.githubusercontent.com/u/3103859?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/micku7zu",
    "html_url": "https://github.com/micku7zu",
    "followers_url": "https://api.github.com/users/micku7zu/followers",
    "following_url": "https://api.github.com/users/micku7zu/following{/other_user}",
    "gists_url": "https://api.github.com/users/micku7zu/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/micku7zu/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/micku7zu/subscriptions",
    "organizations_url": "https://api.github.com/users/micku7zu/orgs",
    "repos_url": "https://api.github.com/users/micku7zu/repos",
    "events_url": "https://api.github.com/users/micku7zu/events{/privacy}",
    "received_events_url": "https://api.github.com/users/micku7zu/received_events",
    "type": "User",
    "site_admin": false
  },
  "html_url": "https://github.com/micku7zu/vanilla-tilt.js",
  "description": "A smooth 3D tilt javascript library.",
  "fork": false,
  "url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js",
  "forks_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/forks",
  "keys_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/teams",
  "hooks_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/hooks",
  "issue_events_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/issues/events{/number}",
  "events_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/events",
  "assignees_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/assignees{/user}",
  "branches_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/branches{/branch}",
  "tags_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/tags",
  "blobs_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/languages",
  "stargazers_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/stargazers",
  "contributors_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/contributors",
  "subscribers_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/subscribers",
  "subscription_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/subscription",
  "commits_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/contents/{+path}",
  "compare_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/merges",
  "archive_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/downloads",
  "issues_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/issues{/number}",
  "pulls_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/labels{/name}",
  "releases_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/releases{/id}",
  "deployments_url": "https://api.github.com/repos/micku7zu/vanilla-tilt.js/deployments",
  "created_at": "2017-01-27T18:32:50Z",
  "updated_at": "2022-12-17T08:03:55Z",
  "pushed_at": "2022-12-12T23:26:22Z",
  "git_url": "git://github.com/micku7zu/vanilla-tilt.js.git",
  "ssh_url": "git@github.com:micku7zu/vanilla-tilt.js.git",
  "clone_url": "https://github.com/micku7zu/vanilla-tilt.js.git",
  "svn_url": "https://github.com/micku7zu/vanilla-tilt.js",
  "homepage": "https://micku7zu.github.io/vanilla-tilt.js/index.html",
  "size": 508,
  "stargazers_count": 3309,
  "watchers_count": 3309,
  "language": "JavaScript",
  "has_issues": true,
  "has_projects": true,
  "has_downloads": true,
  "has_wiki": true,
  "has_pages": true,
  "has_discussions": false,
  "forks_count": 173,
  "mirror_url": null,
  "archived": false,
  "disabled": false,
  "open_issues_count": 19,
  "license": {
    "key": "mit",
    "name": "MIT License",
    "spdx_id": "MIT",
    "url": "https://api.github.com/licenses/mit",
    "node_id": "MDc6TGljZW5zZTEz"
  },
  "allow_forking": true,
  "is_template": false,
  "web_commit_signoff_required": false,
  "topics": [
    "javascript",
    "library",
    "smooth",
    "smooth-animations",
    "smooth-effect",
    "tilt",
    "tilt-effect",
    "tilt-javascript",
    "tiltjs",
    "vanilla",
    "vanilla-javascript"
  ],
  "visibility": "public",
  "forks": 173,
  "open_issues": 19,
  "watchers": 3309,
  "default_branch": "master",
  "temp_clone_token": null,
  "network_count": 173,
  "subscribers_count": 33
}})
